# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZ9aEpYTGhbvabQmGqscgNVpCe8G2AeR
"""

# -*- coding: utf-8 -*-
"""Linear Regression Deployment on streamLit .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19X1VJGfFofHO5mMV-ohidfL3mrN_Jj8a
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
import streamlit as st

st.markdown("---")
st.markdown(
    "[GitHub](https://github.com/Akanksha549) | "
    "[LinkedIn](https://www.linkedin.com/in/akanksha-mishra-7894912bb) "
)


# -----------------------------------
# Page Configuration
# -----------------------------------
st.set_page_config(
    page_title="Insurance Age Prediction",
    layout="centered"
)

st.title(" Insurance Age Prediction")
st.write("Predict insurance purchase age using Logistic Regression")

# -----------------------------------
# Load Dataset
# -----------------------------------
df = pd.read_csv("insurance_data.csv")

st.subheader("Dataset")
st.dataframe(df)

# -----------------------------------
# Train Model
# -----------------------------------
X = df.drop("age", axis=1)
y = df["age"]

model = LogisticRegression()
model.fit(X, y)

# -----------------------------------
# User Input
# -----------------------------------
st.subheader("Enter age")

age = st.number_input(
    "Age",
    min_value=10,
    max_value=65,
    value=18,
    step=1
)

# -----------------------------------
# Prediction
# -----------------------------------
if st.button("Predict Insurance Choice"):
    prediction = model.predict([[age]])

    if prediction[0]==0:
        result="No"
    else:
        result="Yes"
    st.success(f"Insurance Purchase Prediction: {result}")st.success(f"Age Prediction: {result}")
